name: PR Maintainer Bot
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  update-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Post questionnaires as comments (do not inject maintainer block)
        uses: actions/github-script@v6
        with:
          script: |
            async ({ github, context, core }) => {
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              const pr = context.payload.pull_request;
              if (!pr) { core.info('No pull_request in context; exiting.'); return; }
              const prNumber = pr.number;
              const prAuthor = pr.user.login;
              const actor = context.actor;

              // Read approvers file (if present)
              let approvers = [];
              try {
                const resp = await github.repos.getContent({
                  owner,
                  repo,
                  path: '.github/PAR_APPROVERS',
                  ref: context.payload.pull_request.base.ref
                });
                const content = Buffer.from(resp.data.content, 'base64').toString();
                approvers = content.split('\n').map(s => s.trim()).filter(Boolean);
              } catch (e) {
                core.info('.github/PAR_APPROVERS not found or unreadable; treating as empty list.');
              }

              // Prepare questionnaires (comments only)
              const parQuestionnaire = [
                '### PAR Approval Checklist',
                '1. Is this change covered by an existing PAR?',
                '2. If not, has a new PAR been filed and approved?',
                '3. Approver login:',
                ''
              ].join('\\n');

              const bypassQuestionnaire = [
                '### Bypass PAR Approval Questionnaire',
                '1. Explain why a PAR approval should be bypassed for this PR.',
                '2. Risk assessment and mitigation steps:',
                ''
              ].join('\\n');

              // Post comments according to actor; do NOT inject maintainer-only fields into PR body here
              const comments = [];
              if (actor === prAuthor) {
                comments.push(bypassQuestionnaire);
              }
              if (approvers.includes(actor)) {
                // PAR approver sees both
                comments.push(parQuestionnaire);
                comments.push(bypassQuestionnaire);
              }

              for (const c of comments) {
                await github.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: c
                });
                core.info('Posted questionnaire comment.');
              }
            }